// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC24wcOUyApDNRMmFR9BYKwZh1NQQQ-umk',
    appId: '1:968134642071:web:f07591b5277a7cf9969cd2',
    messagingSenderId: '968134642071',
    projectId: 'flutter-firebase-auth-bl-3a58c',
    authDomain: 'flutter-firebase-auth-bl-3a58c.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-bl-3a58c.appspot.com',
    measurementId: 'G-VYNMHGPB7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ItIqULgOiGCVXufo_PPOVXSOHfJv-Oc',
    appId: '1:968134642071:android:dcad4998418192bf969cd2',
    messagingSenderId: '968134642071',
    projectId: 'flutter-firebase-auth-bl-3a58c',
    storageBucket: 'flutter-firebase-auth-bl-3a58c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmSsxonANvDQ_OBnF7_KUSz43jCjp5hiQ',
    appId: '1:968134642071:ios:c8cd794cdfc5e0d6969cd2',
    messagingSenderId: '968134642071',
    projectId: 'flutter-firebase-auth-bl-3a58c',
    storageBucket: 'flutter-firebase-auth-bl-3a58c.appspot.com',
    iosClientId: '968134642071-doeajm39h31vga1iohe9tls9ppo6s4t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmSsxonANvDQ_OBnF7_KUSz43jCjp5hiQ',
    appId: '1:968134642071:ios:c8cd794cdfc5e0d6969cd2',
    messagingSenderId: '968134642071',
    projectId: 'flutter-firebase-auth-bl-3a58c',
    storageBucket: 'flutter-firebase-auth-bl-3a58c.appspot.com',
    iosClientId: '968134642071-doeajm39h31vga1iohe9tls9ppo6s4t1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuthBloc',
  );
}
